//
// Generated file, do not edit! Created by nedtool 5.6 from ND.msg.
//

#ifndef __ND_M_H
#define __ND_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ND.msg:17</tt> by nedtool.
 * <pre>
 * message ND
 * {
 *     int src;
 *     int neighbor;
 * 
 * }
 * </pre>
 */
class ND : public ::omnetpp::cMessage
{
  protected:
    int src;
    int neighbor;

  private:
    void copy(const ND& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ND&);

  public:
    ND(const char *name=nullptr, short kind=0);
    ND(const ND& other);
    virtual ~ND();
    ND& operator=(const ND& other);
    virtual ND *dup() const override {return new ND(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrc() const;
    virtual void setSrc(int src);
    virtual int getNeighbor() const;
    virtual void setNeighbor(int neighbor);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ND& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ND& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ND_M_H

